name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Running asdf's plugin-test with bazelisk
        uses: asdf-vm/actions/plugin-test@v2.2.0
        with:
          command: bazelisk --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Running asdf's plugin-test with bazel
        uses: asdf-vm/actions/plugin-test@v2.2.0
        with:
          command: bazel --version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
