name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test: # make sure the action works on a clean machine without building
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        tool_versions:
          - |
            path:.

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          tool_versions: ${{ matrix.tool_versions }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: rtx --version
      - run: rtx exec -- bazelisk version
      - run: command -v bazelisk
      - run: bazelisk version

      - run: rtx exec -- bazel version
      - run: command -v bazel
      - run: bazel version
