name: lint

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          tool_versions: |
            shellcheck 0.9.0
      - run: shellcheck -x bin/* -P lib/

  shellfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
        with:
          tool_versions: |
            shfmt 3.7.0
      - name: Run shfmt
        run: shfmt -d .
